### PR TITLE
Arm64 ci 2

### LINKED ISSUE #131: ARM64 support
from https://github.com/numenta/nupic.core/issues/1439 

Check if we can build on Arm64 too. 
Should be easier, as ASM and platform specific code was mostly removed. 
- [ ] solve compiler differences
- [ ] possible cmake changes 
- [x] is there a free arm CI?  -> moved to #134 

Thanks for testing when you have time, @paulscode

### PR DESCRIPTION
**Pull request by breznak**
Fixes #131

### CODE REVIEW

**Comment by breznak** [comment]
@brev @dkeeney please have a look at the Docker, CI if you want. 
Let's continue the ARM64 build fixes here.

**Comment by breznak** [comment]
@brev do you know why the pip numpy version mismatch is happening? 
I reproduce the same bug when I build Docker locally for x86. 

As David said, the Docker runs `pip install -r requirements.txt` before any build. the requirements.txt explicitely states numpy>=1.12, and hexy, and hexy needs numpy >=1.15, so it should install that. 

A workaround would be to explicitely state numpy>=1.15 (1.16 is current avail). Any objection to that move, @dkeeney ?

**Comment by dkeeney** [comment]
no objection to going to at least numpy 1.15.0
Of course we would need to try it with python code to see if it breaks anything.  Do we have our .py code complete enough to do python unit tests?

**Comment by breznak** [comment]
Thank you, David! 
- [x] Now ARM64 builds fine :heavy_check_mark: , 
- [ ] next easy step is to make tests execute 
- [ ] and make the build faster (takes 4hrs!!) and/or scheduled only 1x daily

**Pull request merged**
