### PR TITLE
Groupby cleanup

### PR DESCRIPTION
**Pull request by breznak**
keeping only the variant we use: TM uses 3-sequences. 
All other overloads are removed. 

For #263

### CODE REVIEW

**Comment by ctrl-z-9000-times** [comment]
Can we get rid of groupby altogether and just inline it?  IIRC its only used in one place and it has a todo note to better explain it.  

Putting the implementation of it directly in the source should make it clearer what its doing. So we wouldn't need to explain it.

**Comment by breznak** [comment]
> Can we get rid of groupby altogether and just inline it? IIRC its only used 

We could get rid of the GroupBy.hpp, iterGroupBy is indeed only used in that one place in TM, so it should be TM's private method. 
On the other hand it has unit tests, which are easier if it's a standalone file. Also the function is still quite lengthy and complicated, so I'd prefer not to further bloate TM.cpp with it. But no strong opinion there. 

Ideal would be to replace with a 3rd party lib, #263 later

**Comment by breznak** [comment]
Thanks. If you agree, please ACK and we can merge this PR.

**Comment by breznak** [comment]
>  I still think that at some point in the future groupBy should be merged directly into the TM. Most of the code here are templates and boilerplate 

I'll see if I can do that quickly. 
First step would be moving `activateCells` from C-style array to SDR, and the we can use groupBy, not iterGroupBy, removing all the Iterator code. 
Next would be removing the templates and then the function can easily be moved to TM.

**Comment by ctrl-z-9000-times** [comment]
@breznak,

What I was thinking of doing was simply copy-pasting the method iterator::next into the method activateCells.  I don't think that using SDRs is critical for this section of code because regardless of SDR vs C-array, its going to be operating on the sparse data format where standard iterators work the same.

But what you describe should also work and I'm all for it, although I think it would be more work to do.

Regardless of this future work, I would recommend hitting that merge button before either the build breaks or a contentious issue arises.  Thank you for cleaning up this area of the code!

**Comment by breznak** [comment]
Thank you for reviews. You were right, merged this and submiting a consequent PR that diverged slightly :)

**Pull request merged**
