### PR TITLE
Using unique_ptr for Region.

### PR DESCRIPTION
**Pull request by dkeeney**
This still will not pass Python Tests because the Collection calls are missing. Will fix.

This uses the unique_ptr for the Region. I will need to do this for Link as well.  This works.  It does make sure that the Region gets deleted if the region is removed from the collection. But there is a catch.   **A unique_ptr cannot be copied.**  That means that anything that contains it cannot be be copied so the copy constructor on the Network object had to be disabled.  This means that the region object or the Network object cannot be copied.  For example, 
    Network net = Network();
will fail.  Also, cannot pass the object by value...must be a reference to the object so it cannot be created in a function and returned to the function's caller as was done in one of he tests.  Consequently you will see that I am still passing the pointer to Region everywhere.  I could pass a reference to the unique_ptr as in   RegionPtr& r  but why not just pass Region *.

I also discovered that the Collection object does a serial lookup.  I replaced it with just a plain std::map.  However, that breaks the API and the unit tests have to change.  So I will have to go back and fix the Collection I guess.

So, given the 'cannot copy' restriction on std::unique_ptr, do you think this is still the right way to go?

### CODE REVIEW

**Comment by dkeeney** [comment]
Make this two PR's.
- Fix Collection (for use with Spec)
- Decide how to handle Region* and Link* (and possibly Input*, Output*) Probably a separate map with smart pointers.

**Comment by breznak** [comment]
> This uses the unique_ptr for the Region. I will need to do this for Link as well. This works. It does make sure that the Region gets deleted if the region is removed from the collection. 

So this is the advantage of unique_ptr

> That means that anything that contains it cannot be be copied so the copy constructor on the Network object had to be disabled. This means that the region object or the Network object cannot be copied 

And this is against it. I assume with the shared_ it's the other way around. 

> I also discovered that the Collection object does a serial lookup. I replaced it with just a plain std::map. However, that breaks the API and the unit tests have to change. So I will have to go back and fix the Collection I guess. 

Map sounds good. How serious API break is it? My point is whether it's worth it, as there aren't that many objects in the Collection...

> Fix Collection (for use with Spec) 

What is Spec here? 

> Decide how to handle Region* and Link* (and possibly Input*, Output*) Probably a separate map with smart pointers. 

So the problem is we cannot pass smart ptr to python? Current option is passing raw pointer, and what you use is passing a string "id"? Sounds quite simple and even more transferable approach (the ID is :+1: ) 

> So, given the 'cannot copy' restriction on std::unique_ptr, do you think this is still the right way to go? 

I'm not sure, if shared_ didn't have any of the problems (?)

**Comment by dkeeney** [comment]
It depends on what we want to do. If the only objective is to make sure a
region gets deleted then unique ptr does the job. Although the collection
object could do that job as well. The raw pointer is still passed around.

If the objective is to make sure nothing will crash using a deleted pointer
then you need to pass the shared_ptr around and place that on every object
that holds region references. This keeps the pointer active.

Another alternative is to put the region’s name in referancing objects and
do a key lookup in the region collection map to get the region pointer when
needed. A deleted pointer will still be gone but the using class would know
it.

**Comment by breznak** [comment]
> The bindings assume Region pointers are replaced with shared_ptr. I am thinking it is a good idea. If the .py code should use a raw pointer after a Region has been removed, it would crash so this gives some protection. I coded up shared_ptr's for Regions before but had problems with SWIG. Now that SWIG is gone perhaps this will be easy this time. Same for Links.

Do you want to revisit this PR? 

Or better, if it can wait after pybind pr

**Comment by dkeeney** [comment]
> Or better, if it can wait after pybind pr

Well, it is already in and it compiles.  I will leave the Collection rework for another PR.
I will do another progress push on the pybind11_part2.

**Comment by dkeeney** [comment]
Region and Link have been outfitted with std::shared_ptr in the pybind11-part3 PR so this PR and its branch can be discarded.

**Comment by breznak** [comment]
> so this PR and its branch can be discarded. 

@dkeeney you've put this as "on hold", do you want to close it, or revisit later? I don't know what (else) may have been in this PR. 
Probably too many merge conflicts in this PR, closing now and we can reopen if needed.

**Comment by dkeeney** [comment]
We can discard this one.  It was one of those rabbit holes that did not arrive at a solution.

**Comment by dkeeney** [comment]
We do need to go back and fix collections...probably using a std::map as the base.  But lets use a new branch.  I will add an issue so we don't forget.

**Pull request closed without merging**
