### PR TITLE
Anomaly likelihood

### PR DESCRIPTION
**Pull request by breznak**
`Likelihood` is an alternative method of anomaly computation, ported from Python repo. 

Beta work, please review for high level functionality! :+1: 

TODO:
- [x] port all required methods/functionality
  - [x] fix syntax
  - [x] improve "API" design, methods' signatures,... 
  - [ ] fix formatting
- [x] integrate into nupic's cmake build system
- [ ] port tests from tests/unit/.... in nupic-PY #124 
- [x] create a header file (at the end, when everything is cleaned up) 
- [x] integrate into `Anomaly` class - ~~almost, some PROBLEMS *)~~
- [x] resolve CI/platform errors
  - [x] Win/Bamboo: [1](https://ci.appveyor.com/project/numenta-ci/nupic-core/build/0.3.0.2009/job/h5lr86x3o8808i1a#L1144)
- [ ] at the very last, rebase commits and squash them to more compact pieces
- [x] use SlidingWindow #1277 instead of boost::CircularBuffer after it's merged
- [ ] consider inheriting from `Anomaly` and defining proper constructor, https://github.com/numenta/nupic.core/pull/1268#discussion_r117609072 
- [ ] consider `reset()` for Likelihood, https://github.com/numenta/nupic.core/issues/1267#issuecomment-302876334 
- [x] honoring the `timestamp`, as in https://github.com/numenta/nupic.core/pull/1268#discussion_r117609809
- [ ] discuss `removing aggregation` functionality from Likelihood https://github.com/numenta/nupic.core/pull/1268#issuecomment-302908546 

Fixes #1267 
Moved from https://github.com/numenta/nupic.core/pull/1268 
! the issues/links in this description won't work, please follow the original PR for the references.

### CODE REVIEW

**Comment by breznak** [comment]
@dkeeney @ctrl-z-9000-times @Thanh-Binh please review if you have time, this could be merged to community now

**Comment by dkeeney** [comment]
Hmmm, missed the fact that it did not pass the Python tests.  This has something to do with Cells4.  Did this indirectly change something in Cells4 somehow?

**Comment by breznak** [comment]
Tests pass ok locally,
This is something in the CI with the bindings, happens with all other PRs
as well. I’m suspecting some caching/artifacts

-- 
Marek Otahal :o)

**Comment by ctrl-z-9000-times** [comment]
Great work breznak!

My only worry is the unit tests aren't all there yet: `//TODO port likelihood tests`.  If you don't want to do this task now then I would recommend documenting the task and leaving it for later.  Just open an issue for this TODO note after this PR is merged.

**Comment by breznak** [comment]
> My only worry is the unit tests aren't all there yet: //TODO port likelihood tests. If you don't want to do this task now then I would recommend documenting the task and leaving it for later 

Thanks for review @ctrl-z-9000-times ! Yes, it's an old PR, I'm not using it currently, just want it merged so other people can. Opened #124 with TODO tests

**Comment by breznak** [comment]
Do you have an idea why this is failing? The PR doesn't touch any Region/python stuff. Passes OK an my linux locally, could you please test? 

https://travis-ci.org/htm-community/nupic.cpp/builds/460796412#L5470

**Comment by breznak** [comment]
Assuming prev OK, this is finally merged too!

**Pull request merged**
