### PR TITLE
Py detect Anaconda

### PR DESCRIPTION
**Pull request by breznak**
- and fail unsupported

For debugging #436

### CODE REVIEW

**Comment by breznak** [comment]
FYI @dkeeney

**Comment by fcr** [comment]
Hi,
FYI, I just successfully built the head branch using Anaconda on my Mac. (I had to comment out the lines that flag anaconda as unsupported to do it, of course).

It passed all tests except the timing tests:
/Users/fred/Development/nupic.cpp/src/test/unit/algorithms/ConnectionsPerformanceTest.cpp:185: Failure
Expected: (tim) <= (3.3f*Timer::getSpeed()), actual: 3.38798 vs 3.3
[  FAILED  ] ConnectionsPerformanceTest.testTM (4511 ms)

ERR:  CHECK FAILED: "timeTotal <= CI_avg_time" HelloSPTP test slower than expected! (34,should be 30), speed coef.= 1 [/Users/fred/Development/nupic.cpp/src/examples/hotgym/HelloSPTP.cpp line 222]
unknown file: Failure
C++ exception with description "CHECK FAILED: "timeTotal <= CI_avg_time" HelloSPTP test slower than expected! (34,should be 30), speed coef.= 1" thrown in the test body.

As a proof of viability, I ported a the old nupic.vision.ocr application to run with the build under Python 3.7 and it ran correctly **except** that  SpacialPooler.getPermanence() always returned zero values.

These are the commands that I used:
export ARCHFLAGS="-arch x86_64"
export MACOSX_DEPLOYMENT_TARGET=10.14

python setup.py install --user --force

My environment is MacOS 10.14.5 with Anaconda for Python 3.7.
I have attached a list of all the Python packages that are installed, as well all the MacPorts, in case you are interested in duplicating this.

[myconda.txt](https://github.com/htm-community/nupic.cpp/files/3224066/myconda.txt)
[myports.txt](https://github.com/htm-community/nupic.cpp/files/3224067/myports.txt)

**Comment by breznak** [comment]
> FYI, I just successfully built the head branch using Anaconda on my Mac. (I had to comment out the lines that flag anaconda as unsupported to do it, of course)

Wow @fcr ! this is nice news. 
Thank you very much for confirmation, and we'll make a PR affirming anaconda support again. (or you can make a PR if you can) 

> It passed all tests except the timing tests: 

timing test failures are fine, runs reliably only on Linux CI. 

> As a proof of viability, I ported a the old nupic.vision.ocr application to run with the build under Python 3.7 and it ran correctly 

hey, this is even better news! So your python API is stable enough to be used with the old code! Good to have this confirmation. 

> except that SpacialPooler.getPermanence() always returned zero values. 

can you have a look into this, or we'll open a bug to investigate. I'd suspect the binding
`bindings/py/cpp_src/bindings/algorithms/py_SpatialPooler.cpp`, or that the SP is not processing your data correctly in the experiment?

**Comment by fcr** [comment]
I'll post a PR for the Anaconda support .
I'll try and look into the SpacialPooler assuming I understand how the bindings are generated.

**Comment by breznak** [comment]
That's great! Let me know or @dkeeney if you need some help with pybind. 

> I'll try and look into the SpacialPooler assuming I understand how the bindings are generated. 

can you have a look if we actually have a unit test for the problematic method, to verify the bindings work well.

**Pull request merged**
