### PR TITLE
Upgrade YamlCpp to new 0.5 API

### PR DESCRIPTION
**Pull request by breznak**
YAML is a dependency, update to latest version, fix breaking changes as they moved to new API. 

Fixes #1319 #33 
Moved from https://github.com/numenta/nupic.core/pull/1320 

Todo: 
- [x] do the porting in `Network.cpp`, see the issue for details and help. 
- [x] port YAMLUtils
- [x] resolve issue in CI (not reproducible locally) with linking `Boost`
  - [x] by upgrading to YamlCpp 0.6 (c++11, no boost dependency)

### CODE REVIEW

**Comment by breznak** [comment]
https://ci.appveyor.com/project/numenta-ci/nupic-core/build/0.3.0.2255/job/tpqniaraoo0ctifo#L1172
a problem of the CMakeFile not setting up boost includes properly, or is it missing on the CI machines? (but it shouldn't matter, as we ship the boost headers ourselves).
I don't observe this on my system.
Likely with the update to YAML 0.5.7, we will be interested in the new release jbeder/yaml-cpp#415 that will not depend on boost. So workaround introduced now can then be removed.

**Comment by breznak** [comment]
@chhenning @mattheller if you are running Windows, do you think you could try having a look in to the problem?

**Comment by chhenning** [comment]
Good news is that your code changes are working on my Windows machine. Great work! I have internally upgraded to yaml-cpp 0.5.3.

Bad news is that I cannot really help with cmake. Sorry.

**Comment by breznak** [comment]
@rhyolight should I tag you for changes like this that could be backported upstream to numenta, or you'll be watching out yourself?

**Pull request merged**
