### PR TITLE
Grid Cell Encoder Cleanup

### PR DESCRIPTION
**Pull request by ctrl-z-9000-times**
For issue #399:
- Added titles to the displayed figures, as well as a brief explanation.
- I did not move the plotting code into its own method. I just don't see the utility of having two ways to call that code, since it already has a good user interface, via the command line.

For issue #400:
- GridCellEncoder.encode now accepts two arguments, like:
    + `enc.encode( X, Y )`
    + `enc.encode( CoordinateList )`  - still works

I think this should resolve both issues.

### CODE REVIEW

**Comment by breznak** [comment]
CI: the UNIXes are unhappy with the `*args` python syntax

> ==================================== ERRORS ====================================
________ ERROR collecting py/src/nupic/tests/encoders/grid_cell_test.py ________
/Users/distiller/Library/Python/2.7/lib/python/site-packages/_pytest/python.py:512: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/Users/distiller/Library/Python/2.7/lib/python/site-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
/Users/distiller/Library/Python/2.7/lib/python/site-packages/_pytest/assertion/rewrite.py:301: in load_module
    exec(co, mod.__dict__)
encoders/grid_cell_test.py:26: in <module>
    from nupic.encoders.grid_cell_encoder import GridCellEncoder
E     File "/Users/distiller/numenta/nupic.core/build/Release/distr/src/nupic/encoders/grid_cell_encoder.py", line 87
E       def encode(self, *args, grid_cells=None):
E                                        ^
E   SyntaxError: invalid syntax
- generated xml file: /Users/distiller/numenta/nupic.core/py/src/nupic/tests/junit-test-results.xml -

**Comment by ctrl-z-9000-times** [comment]
Oops, I did not test with python2.  This is not valid syntax in python2.  Can we drop support for python2 and use python3 only?

**Comment by breznak** [comment]
> Can we drop support for python2 and use python3 only?

that is a bigger drop right here. Eventually definitely, but I'm not sure for now, as a lot of projects in the ecosystem still uses (only) py2. 
So I'd rather not. Is there a way you could do this in the meanwhile?

**Comment by ctrl-z-9000-times** [comment]
> a lot of projects in the ecosystem still uses (only) py2.

They should not still be using python2.  It goes end of life at the end of this year.  Everyone should be moved or in the process of moving to python3.  Python2 packages (such as numpy) have already found security vulnerabilities and declared that they will not fix them because its too close to the end of life.

We currently have few users since most of them still use numenta's nupic.  When they switch to our nupic they will need to rewrite some of their code anyways so it makes sense to force them into using python3 at that time.

**Comment by breznak** [comment]
> They should not still be using python2. It goes end of life at the end of this year

let's discuss this separately of the PR, 

what I want to say is that python 2 has its ecosystem- there are libraries, even outside HTM, that work with py2, and we now offer the ability to work with those codes. (HTM repo is a research thing, I don't think it's so much on us to force "good security behavior" on us). I don't want to lose the ability for a minor cleanup PR, so unless its inevidable, let's support both.

**Comment by dkeeney** [comment]
> so unless its inevidable, let's support both.

I think I agree with @breznak.  Even though it is a pain we should continue to be compatible with Python2 for a while after end-of-life.

**Comment by ctrl-z-9000-times** [comment]
I removed all of the issues with python2.  Now this PR will only resolve issue #399.

**Pull request merged**
