### PR TITLE
Add Sliding window

### PR DESCRIPTION
**Pull request by breznak**
Add class providing fast & reusable sliding window implementation 

- [x] simplifies MovingAverage
- [x] improves compare==
- [x] fix CI error
- [ ] old,long PR, squash commits before merging

Fixes #1276 
Moved from https://github.com/numenta/nupic.core/pull/1277 
Please see discussion there

### CODE REVIEW

**Comment by breznak** [comment]
This should be an easy one, heavily reviewed PR back from Numenta. Add sliding window/circular buffer implementation. 
If you see a place where this could simplify code, feel free to put it there.

**Comment by dkeeney** [comment]
I was going to replace the circular buffer with a simple std::deque.
@Christian
Henning <chhenning@gmail.com> had a boost::circular_buffer which is
actually a better fit but almost the same as a std::deque. Either of these
two things is basically the same as a sliding window since we are using an
Array object with a shared pointer to the real buffer.  But I will look at
their implementation.

**Comment by breznak** [comment]
Good point, I was using boost::circular_buffer too, this sprang to life just to get rid of it. 
Deque is ofc a good fit, I think we've used it..and later this evolved to fit some sugar with operators etc.

**Comment by dkeeney** [comment]
Oh...after looking at the Numenta issues. We are not talking about the same
thing.   I am talking about the use of a circular_buffer in the Link to
handle Propagation Delay.  You are talking about the MovingAverage
function.  Very different.
However, if you can use a boost::circular_buffer there you could also use a
std::deque and avoid the extra dependency.

**Comment by breznak** [comment]
@dkeeney please review, if merging, merge as "Squash and merge" this time, to avoid all the fixup commits

**Comment by breznak** [comment]
..I forgot to implement serialization, dig into it and got stuck on possible design flaw in Serializable (I have problem serializing any object with const member, as serialization assumes default constructor())

**Comment by breznak** [comment]
Will merge as is, and do the Serialization etc in other PR. 

> Perhaps you could overload [ ] operator and remap the index such that it always indexes in order. Do the same with the iterator. Then you would not need the getLinearizedData() function and data will always be in queue order. getData() would require copying into a new vector so it would be ordered. 

I like this idea. Will add it to comment in that file and revisit when we finish other things in progress

**Pull request merged**
