### PR TITLE
WIP SparseMatrix removal

### LINKED ISSUE #104: Investigate removal of custom math/*Matrix;
There is a huge ammount of code in `math/*Matrix` that is old, unmaintained and quite untested. Propose removal and replacement : 

- replace with Connections
- or Eigen #42  
- or keep only the SparseBinaryMatrix

Look at the problem and proposed order of progress: 

`grep -R 'Matrix' src/nupic/math/ | cut -d: -f1 |sort -u`
- [ ] src/nupic/math/Math.hpp 
- [ ] src/nupic/math/ArrayAlgo.hpp -- maybe most of its methods will be removed? 
- [ ] src/nupic/math/DenseMatrix.hpp -- only one user SDRClassifier, replace with sparse & rm first #170  #169 
- [x] src/nupic/math/NearestNeighbor.hpp -- NN does not have to be in a HTM codebase
- [ ] src/nupic/math/SparseBinaryMatrix.hpp -- heavily used in SP #93 , #169 
- [x] algorithms/CondProbTable -- rm too? Uses:
  - [x] src/nupic/math/SparseMatrix01.hpp -- not used, rm
- [ ] src/nupic/math/SparseMatrix.hpp -- huge, untested, suprisingly not a base of SparseBinaryM #169 
  - used in ArrayAlgo, DenseMatrix, SpatialPooler
- [x] src/nupic/math/SparseMatrixAlgorithms.hpp -- not used, rm
- [x] src/nupic/math/SparseMatrixConnections.hpp -- not used, rm
  - [x] src/nupic/math/SegmentMatrixAdapter.hpp -- used only in SMConn
    - [x] py_SegmentSparseMatrix
- [x] src/nupic/math/SparseRLEMatrix.hpp -- not used, rm
- [ ] src/nupic/math/SparseTensor.hpp -- not sure how needed for Py  - implemented (but reverted) here:  bfb58df  , #169 
  - [ ] Domain
  - [ ] Index
  - [ ] PyBindSparseTensor 
- [x] math/Math.hpp:Gaussian_2D -- not used, further cleanup Math.hpp

Related:
 - #93 SP on Connections

Prerequisities: 
 - [ ] c++ speed tests #30 
 - [ ] validate Python nupic still compatible with this nupic.core #137

### PR DESCRIPTION
**Pull request by breznak**
fixes #104

### CODE REVIEW

**Comment by breznak** [comment]
@dkeeney please review. 
- Removal of unused classes from math/ Sparse*Matrix (each in separate commit) 
- this should simplify your PY generation 
- removed files are never used in c++ codebase. May have been exported by PY , but I don't see  immediate use (py native libraries, as Numpy are better used) 
- commit  bfb58df  would remove SparseTensor (and its dependencies Index, Domain) but is used once in SparseMatrix; removal deffered for later #93

**Comment by ctrl-z-9000-times** [comment]
So I did a text search through in numenta/nupic.py and found:
SegmentSparseMatrix32 - not found
SparseMatrixAlgorithms - not found
SparseMatrix - found:
* src/nupic/algorithms/spatial_pooler.py - Uses SparseMatrix
* examples/bindings/sparse_matrix_how_to.py - documentation
* docs/source/api/math.rst - documentation
* src/nupic/math/\_\_init\_\_.py - imports it from bindings
* src/nupic/algorithms/knn_classifier.capnp - uses SparseMatrix
* src/nupic/math/stats.py - uses SparseMatrix
* tests/unit/nupic/algorithms/spatial_pooler_compute_test.py - Imports but does NOT use SparseMatrix
* docs/source/contributing/cpp-style-guide.md - Documentation
* src/nupic/regions/sp_region.py - Documentation
* tests/unit/nupic/algorithms/spatial_pooler_unit_test.py - Commented out
* src/nupic/algorithms/fdrutilities.py - Expects SparseMatrix as argument

**Comment by dkeeney** [comment]
Good job.  
Only parts of the SparseMatrix class was removed so we probably have enough of the SparseMatrix class to avoid breaking anyone.  It is interesting that none of the unit tests used SparseMatrix or any of its variants.

Ok, I feel more comfortable about removing these.  And yes, this make my job a lot easier.

**Comment by breznak** [comment]
Thanks for making the throughout check, @ctrl-z-9000-times ! 
I'm happy the cleanup could be merged.

**Pull request merged**
