### PR TITLE
Python3 compatibility

### PR DESCRIPTION
**Pull request by ctrl-z-9000-times**

### CODE REVIEW

**Comment by ctrl-z-9000-times** [comment]
Thanks!

**Comment by ctrl-z-9000-times** [comment]
> So the bindings are now both Py2.7 and Py3 compatible ?

They should be, install with
```
python3 setup.py install --user
```
Tell me if you have any problems with this.  I had a few problems which were fixed by deleting my build directory.

**Comment by dkeeney** [comment]
> python3 setup.py install --user

This is my intention although this has not yet been confirmed that it works.

I need to find a way such that you can do
```
python setup.py install --user
python3 setup.py install --user
```
and have both versions workable.  But the dependencies are not setup quite right so the build system knows to re-compile the bindings.  That was going to be another PR.   The MSVC changes will also be messing with this same code.

**Comment by breznak** [comment]
> and have both versions workable 

I think either, or working is great, having both at a time would be just a sweet bonus

**Comment by dkeeney** [comment]
Agreed.  I was thinking along the lines of being able to test both with one run.  But since py2 is going away probably not worth the effort.

**Pull request merged**
