### PR TITLE
Ci travis: update Xenial & g++7

### PR DESCRIPTION
**Pull request by breznak**
Update Travis CI build environment:
- [x] drop deprecated container and run VM type (remove 'sudo: false')
- [x] use Xenial image
- [x] bump to newer gcc 7 (from old 4.8)
- [x] Release build & -j4

### CODE REVIEW

**Comment by breznak** [comment]
OSX CI tests fail only because we build it now in Debug, fixed in #89

**Comment by breznak** [comment]
@dkeeney might be interesting to your Boost work #85. as it bumps compiler to gcc-7

**Comment by breznak** [comment]
Restart CI to validete OSX now

**Comment by breznak** [comment]
> I noticed that you removed the -DNTA_COV_ENABLED=ON flag from the cmake startup 

This is(was) used for unit-test coverage in CI, effectively only on Travis/Linux. So I left it there, but removed from OSX build. 

> I also noticed that you are doing a "debug" build on circle, but you are putting it into the ../release folder. Will work but perhaps it will be more obvious if you install into the ../Debug folder.

Here I'm just keeping the convention from nupic. Debug/Release are cmake compilation modes, while build/release/ is a path where we output the build. 
I think it would make things more difficult to need to find release-vs-debug folder (?)

**Comment by dkeeney** [comment]
Ok, understood.  I guess I have spent too much time with MSVC where there
are always separate Debug and Release folders.

**Pull request merged**
