### PR TITLE
distribution framework.

### PR DESCRIPTION
**Pull request by dkeeney**
The .py code from `nupic.py repository/py/src/nupic`  is expected to be copied to `nupic.cpp repository/py/src/nupic`.  These files will be included in the distro.

Note that `nupic.py` repository had `test/` and `examples/` at the top directory.  If these are to be included in the distro they may need to be moved into the  `nupic.cpp repository/py/src/nupic` directory so that the package name starts with nupic.  Don't know what the normal practice is for these files.

### CODE REVIEW

**Comment by breznak** [comment]
After this, #353 should work!

**Comment by dkeeney** [comment]
> and make the tests (py/tests/) run from CI

Sure.  Sounds like a reasonable thing to do.

**Comment by breznak** [comment]
> can you please make some "hello world" test, example 

@dkeeney or should we merge this, and let #353 be the example that verifies this works?

**Comment by dkeeney** [comment]
I was researching this to see what it would take to switch to wheels rather than eggs.  But this will take me some time to figure out.  Let's go with this.

the thing is, I am not sure at what level the `test/` directory should be.  Lets try it this way and lets see how well it works.

**Comment by breznak** [comment]
I'll meerge this, it's passing, only failed performance test, which will be bumped in a consecutive PR.

**Comment by breznak** [comment]
Follow up can be i  #370 , thank you :+1:

**Comment by dkeeney** [comment]
I was also getting an error about not getting some sort of pgp key on travis.  Maybe due to you merging while it was still running.  We can ignore it.

**Comment by breznak** [comment]
..yes, that is a merge PR while CI is still running

**Comment by dkeeney** [comment]
We have hackers hangout in a few min.  Are you going to represent us?

**Comment by breznak** [comment]
> We have hackers hangout in a few min. Are you going to represent us? 

Oh!! I've read this now :( Have any of you attended and pitched our progress? :tada:

**Comment by dkeeney** [comment]
Ok, I did my part and at least said something.  I am not a very good orator so not good at pitching anything but at least we had some visibility.   But check out what Matt said at the very beginning.  It might have a huge impact on us.

**Comment by breznak** [comment]
> I did my part and at least said something. 

That's perfect! Thank you very much. It's important we have someone to show up and say what we're up to. 

> But check out what Matt said at the very beginning. It might have a huge impact on us. 

Show me!! :D Can you post a link, or tag me on Discourse, please?

**Comment by dkeeney** [comment]
https://discourse.numenta.org/categories.  At the bottom is "Talks and Events".  That takes you to a list of all of the talks.  and _"HTM Hackers' Hangout - Apr 5, 2019"_ goes to
https://discourse.numenta.org/t/htm-hackers-hangout-apr-5-2019/5735

**Pull request merged**
