### PR TITLE
Eigen speed

### PR DESCRIPTION
**Pull request by breznak**
Small example using Eigen
- [x] add Eigen support 
- [x] example code optimization

Overall performance might actually be worse, as we need to convert to/from eig. matrix. 

Relevant #3 
Replaces #14 
After #30

### CODE REVIEW

**Comment by breznak** [comment]
@dkeeney please review when you have time, this merely prepares the codebase for using Eigen, with some usage examples in ArrayBase. Should we merge and continue optimizations in other PR, or make it all part of this one? 

@chhenning  did you mention you use eigen optimizations in your fork? Do you have many of them and what is your experience (speedup, portability, simplicity...?) Can I pull them here? 

@ctrl-z-9000-times I figured the ArrayBase class has overlaps with your SDR (#113 ), if you start finding usages and applying SDR to codebase, please have a crack at ArrayBase? : 
- remove what is not (barely) needed (eg copy() routines), and replace with std::
- get_dense_from_sparse, ... -drop, and use your SDR class instead 
- this class is very old and quite unmaintained, the more is removed, the better.

**Comment by dkeeney** [comment]
The ArrayBase (actually the Array class) is the object that passes SDR arrays between Regions (via Links) within the Network framework.  Be aware that this is used for non-SDR arrays of various types as well so some thought needs to be put into how we do this.   Also note that some Regions are implemented as Python and some in C++ and the Array class passes data between them.

**Comment by breznak** [comment]
@dkeeney @ctrl-z-9000-times please review if you have time, I'd like to merge before the big pybind changes

**Comment by breznak** [comment]
> If this needs to be accessed from Python then I will have to figure out how to setup the bindings. 

I think Eigen matrices work well with python, we can pass *array.

**Comment by breznak** [comment]
@dkeeney @ctrl-z-9000-times please consider this header library if you deal with some large vectors/matrices (dense or sparse) or where speed should be an issue. Or at least comment the place so we can use it later.

**Pull request merged**
