### PR TITLE
Fixed.  TabError

### PR DESCRIPTION
**Pull request by Lupino**
TabError: inconsistent use of tabs and spaces in indentation

### CODE REVIEW

**Comment by Lupino** [comment]
I can have a try

**Comment by dkeeney** [comment]
I hope to not frighten you away but the entire .py codebase needs to be converted to Python 3.x ... now that we can support it with the nupic.core extension.  So there is LOTs of python work that needs being done.  If you are interested in helping out with that, much of the porting was already done by @chhenning but we need to clean it up make sure it works with the core library work that was just completed.

**Comment by dkeeney** [comment]
Here is a link to @chhenning's work in case you are interested in helping.
https://github.com/chhenning/nupic/tree/master/src/python/python3

**Comment by breznak** [comment]
> Here is a link to @chhenning's work in case you are interested in helping.
https://github.com/chhenning/nupic/tree/master/src/python/python3 

I was reffering to getting python (2.7) run with our bindigns, as there have been, unfortunately, some breaking differences (capnproto, ...) in #137 ; 
then we can move to py 3.

**Comment by Lupino** [comment]
I found a lot differences on branch #169

**Pull request merged**
