### PR TITLE
DON'T MERGE Python code merged to this repo

### PR DESCRIPTION
**Pull request by breznak**
This is a diff of python code (from nupic.py) considered for merging to this repo. 
DO NOT MERGE. This PR is to keep track of the differences (as we progress to reduce the diffs). 

For issues #216 #137

### CODE REVIEW

**Comment by breznak** [comment]
@ctrl-z-9000-times can you update this branch with progress from nupic.py, please? I'm working on bringing some code  to this repo, and running in problems which I realized would probably have been fixed in the py repo. 

Or, do you have a better way of updating than just copy all content from that repo into our /py/ folder in this branch?

**Comment by ctrl-z-9000-times** [comment]
> do you have a better way

It may not be better, but I was intending to port code over as we find needs for it.  If we never find a need for a piece of code, then it never needs to be moved into this repo.  I was also hoping to do code reviews on numenta's code before it's merged.

Eventually, when we're done merging most of numenta's python code into here, we can go through the old code file by file to check that we got all of the useful stuff.

**Comment by breznak** [comment]
>  If we never find a need for a piece of code, then it never needs to be moved into this repo.

sounds fair. Then we probably should delete this branch. (I'd also avoid the problem I ran into that this branch was behind the changes done in nupic.py repo). 

> Eventually, when we're done merging most of numenta's python code into here, we can go through the old code file by file to check that we got all of the useful stuff.

I agree, we should get all the tests, they'd pull most of what's needed and missing. Rest we'd run into by user reports, if ever.

**Comment by breznak** [comment]
Closing and deleting this branch, as its getting out of sync. Any time we need to port something from python nupic (nupic.py), copy code directly from that repo.

**Pull request closed without merging**
