### PR TITLE
combined engine/ and ntypes/ into networkapi/

### PR DESCRIPTION
**Pull request by dkeeney**
This PR merges the engine/ and ntypes/ folders into networkapi/.  This makes it obvious that these files make up the network API.

### CODE REVIEW

**Comment by dkeeney** [comment]
> This does seem a bit messy to me

Well, we removed so many files that ntypes did not have much left.
What about putting ntypes inside networkapi?
Oh, and I can delete NuPIC.cpp and .hpp.  They don't do anything as far as I can tell.

**Comment by breznak** [comment]
> What about putting ntypes inside networkapi?

this is what I've been thinking: networkapi/ntypes/, networkapi/engine/* (or just networkapi/*and the files from engine* ) 

> Oh, and I can delete NuPIC.cpp and .hpp. They don't do anything as far as I can tell.

Aren't those used for version string during python setup.py?

**Comment by dkeeney** [comment]
> Aren't those used for version string during python setup.py?

No.  NnPIC is used as a container for Network objects and I see not reason to have more than one.  I guess it could be used to hold layers if you wanted to have no more than one layer in a Network.

**Comment by dkeeney** [comment]
The NetworkAPI files form a tree.  All are types.  Keeping some objects in ntypes and others not, does not seem important and rather arbitrary.  But if you seem to see those as something different somehow we can leave it as it is.

**Comment by dkeeney** [comment]
I have changed my mind about this PR.  I am going to drop it for now.  Perhaps when the networkapi namespace is added we can change the directory structure to match.

**Pull request closed without merging**
