### PR TITLE
Random seed from system time

### PR DESCRIPTION
**Pull request by ctrl-z-9000-times**
Also documentation cleanup.

### CODE REVIEW

**Comment by dkeeney** [comment]
@breznak has not shown up for a while.  I think this PR should be ok so I will go ahead and approve it.

**Comment by ctrl-z-9000-times** [comment]
Thanks!

**Comment by ctrl-z-9000-times** [comment]
>  Did it provide same sequence of "random" numbers without the time-seed?

Yes, the RNG "mt19973" has a default seed of 5489u.

**Comment by breznak** [comment]
> Yes, the RNG "mt19973" has a default seed of 5489u. 

good catch! thanks

**Pull request merged**
