### PR TITLE
BasicType moved to ntypes

### PR DESCRIPTION
**Pull request by breznak**

### CODE REVIEW

**Comment by dkeeney** [comment]
I my PR will handle the casts.

**Comment by breznak** [comment]
> But did you check the casts :) 

you've cought me :) I did not. though I mean we could pay attention to it only in the new code we write..

**Comment by dkeeney** [comment]
Well, the problem is that I am trying to push the PR that fixes all of those casts and you pulled the file out from under me :)

I will see if I can get git to figure this out.

**Comment by dkeeney** [comment]
Sorry, I am going to need some help with this.
GitHub shows that my PR has a conflict.  I tried to pull master into my repository
But when I try to resolve it within my repository it cannot find BasicTypes in ntypes/, it is still in types/.  It also does not show me what the conflict was so I cannot resolve it.

**Pull request merged**
