### PR TITLE
New unit-test SP Test ExactOutput

### PR DESCRIPTION
**Pull request by breznak**

### CODE REVIEW

**Comment by breznak** [comment]
> [ RUN      ] SpatialPoolerTest.ExactOutput
/home/mmm/devel/HTM/htm-community/nupic.cpp/src/test/unit/algorithms/SpatialPoolerTest.cpp:1965: Failure
Expected equality of these values:
  output
    Which is: "SDR( 200 ) 40, 65, 89, 93, 123, 146, 177, 192, 195, 196"
  gold
    Which is: "SDR( 200 ) 93, 31, 40, 68, 169, 164, 87, 132, 34, 120"
[  FAILED  ] SpatialPoolerTest.ExactOutput (296 ms) 

this is result of this test backported to previous master (SP w/o Connections)...which is a good thing -> the mistake is in the test, not in SP

**Comment by breznak** [comment]
> This PR requires that the SP is deterministic. 

This should be truth (even now), given a fixed seed. 

I looked briefly at the hinted implementation: I'd think the sorting is not needed. And SDR_t could be (better?) used for the comparison, instead of string&regex ?

**Comment by breznak** [comment]
Let's extend the scope of this PR to "Deterministic algorithms (SP, TM)" 
- [ ] add such test to TM too (bonus if TP as well) 
- [ ] make the algos deterministic given seed 
  - I though they should have been?! 
  - is random stable across OS, runtime, ... - but we do(?) have tests for that

**Comment by ctrl-z-9000-times** [comment]
Moved to PR #197

**Pull request closed without merging**
